### ISSUE TITLE
Documentation Website

### ISSUE THREAD

**Issue by mammadyahyayev** [mammadyahyayev/keyword-finder#1]
Create static website for documentation

**Comment by MamedYahyayev** [comment]
Some of the documentation tools that allow to write good documentations without html css javascript
https://document360.com/blog/software-documentation-tools/

**Comment by MamedYahyayev** [comment]
https://itnext.io/create-compelling-documentation-with-github-pages-16e4149efe9e

**Comment by MamedYahyayev** [comment]
https://www.youtube.com/watch?v=2R53Y7eP45k
Create application and deploy it netlify
